default: &default
  adapter: postgresql
  encoding: 'utf8'
  pool: 5
  port: 5432
  host: 'localhost'
  username: mat
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: todo_list_development

test:
  <<: *default
  database: todo_list_test

production:
  <<: *default
  database: todo_list_production
